AWSTemplateFormatVersion: '2010-09-09'  
Transform: 'AWS::Serverless-2016-10-31'  
Description: Lambda - Buzz  
Resources:  
  developerlambdaquotes:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: developer-function-buzz
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      Description: Lambda - Buzz
      MemorySize: 128
      Timeout: 7
      Role: >-
        <IAM ROLE ARN>